terragrunt-info parsing improvement
gruntwork-io/terragrunt pull request #2901
Opened 2024-01-19 18:28 UTC by denis256

## Description

Added returning of `terragrunt-info` output in case of error.

Fixes #2885.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### Migration Guide

2024-02-23 10:48 UTC, caspar-ds commented
Hello! Any ideas on when this might end up being merged? Any I can do to help out? Thanks

2024-02-23 10:48 UTC, caspar-ds commented
Hi @denis256 and thanks for the PR that addresses the issue! Any ideas on when this might end up being merged? Anything I can do to help out? Thanks

2024-03-28 09:20 UTC, caspar-ds commented
Hi @denis256 - thanks again! Anything I can do to help with this PR?

2024-03-28 20:13 UTC, caspar-ds approved these changes

2024-04-01 18:43 UTC, levkohimins requested changes
Fdded a few small suggestions

2024-04-01 18:43 UTC, levkohimins commented on cli/commands/terragrunt-info/action.go
> +		return err
```suggestion
		return errors.WithStackTrace(err)
```

2024-04-01 18:43 UTC, levkohimins commented on cli/commands/terragrunt-info/action.go
>  		return err
```suggestion
		return errors.WithStackTrace(err)
```

2024-04-02 17:38 UTC, levkohimins approved these changes
LGTM!

2024-04-04 17:54 UTC, merged