Add flag for disabling dependent modules identification in json-render
gruntwork-io/terragrunt pull request #2918
Opened 2024-01-29 14:08 UTC by denis256

## Description

Included changes:
* Added CLI flag to disable dependent modules identification to speed up json rendering
* Added integration tests and docs

Fixes #2809.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### Migration Guide

2024-03-24 14:17 UTC, ajax-ryzhyi-r commented
Hi @denis256!
Is there a possibility for this PR to be merged? The degraded performance of the `render-json` subcommand is preventing us from upgrading the terragrunt version, so it would be great to see this flag released 🙃

2024-04-01 18:48 UTC, levkohimins requested changes
Added a small suggestion.

2024-04-01 18:48 UTC, levkohimins commented on cli/commands/render-json/command.go
> +		},
```suggestion
		&cli.BoolFlag{
			Name:        FlagNameDisableDependentModules,
			EnvVar:      "TERRAGRUNT_JSON_DISABLE_DEPENDENT_MODULES",
			Destination: &opts.JsonDisableDependentModules,
			Usage:       "Disable identification of dependent modules rendering json config.",
		},
```

2024-04-02 17:39 UTC, levkohimins approved these changes
LGTM!

2024-04-04 18:20 UTC, merged