feat: Adding `stylecheck` lint
gruntwork-io/terragrunt pull request #3354
Opened 2024-08-21 12:18 UTC by yhakbar

## Description

Adds `stylecheck` lints. This ensures that we use idiomatic naming for variables and functions, etc.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added `stylecheck` lints.

2024-08-27 13:17 UTC, yhakbar commented
Moving to in-draft to avoid conflicts with #3338. This does not need to be merged in with any urgency.

2024-09-05 13:41 UTC, denis256 commented on test/integration_json_test.go
> +	tmpEnvPath := copyEnvironment(t, testFixtureRenderJSONMetadata)
Looks like there is an inconsistency in the naming convention for test constants:
testFixtureRenderJSONMetadata - private variable
TestFixtureGetTerragruntSourceHcl - public variable

2024-09-05 14:08 UTC, yhakbar commented
Looks like I have more work to do to unwind merge conflicts with `main`.

2024-09-06 11:53 UTC, levkohimins approved these changes
Awesome! You did a lot of hard work.

2024-09-09 15:14 UTC, yhakbar commented
Almost ready to be marked ready for review, but will wait until some logging improvements go through to avoid making that merge harder.

2024-09-16 16:05 UTC, levkohimins requested changes

2024-09-16 16:08 UTC, levkohimins approved these changes
LGTM!

2024-09-16 16:43 UTC, merged