feat: Adding Strict Package
gruntwork-io/terragrunt pull request #3424
Opened 2024-09-19 19:29 UTC by yhakbar

## Description

Adds `strict` package.

This allows users to opt-in for deprecations as breaking changes in Terragrunt.

Users can either use the global `TG_STRICT_MODE` to make Terragrunt throw an error when it encounters a deprecation, or use the relevant `TG_STRICT_` environment variable to opt-in for a specific deprecation.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added `strict` package.

### Migration Guide

If users would like to make Terragrunt throw an error when it encounters a deprecation, they can set the `TG_STRICT_MODE` environment variable to `true`. 
If they would like to opt-in for a specific deprecation, they can set the relevant `TG_STRICT_` environment variable to `true`.

Neither are required and users can continue to use Terragrunt as they have been.

2024-09-20 16:02 UTC, levkohimins requested changes
1) We repeat twice the flag names and warning texts. To add a new command we will have to make changes to two files. 

https://github.com/gruntwork-io/terragrunt/blob/e09d1b64a0960174a226dd649238c5afcf8e1ffb/cli/deprecated_commands.go#L17-L23
https://github.com/gruntwork-io/terragrunt/blob/e09d1b64a0960174a226dd649238c5afcf8e1ffb/internal/strict/strict.go#L26-L39
https://github.com/gruntwork-io/terragrunt/blob/e09d1b64a0960174a226dd649238c5afcf8e1ffb/internal/strict/strict.go#L80
https://github.com/gruntwork-io/terragrunt/blob/e09d1b64a0960174a226dd649238c5afcf8e1ffb/cli/deprecated_commands.go#L64


2) Why wouldn't we use the CLI package to get strict values, which could also be specified via flags, not only via evn vars. For example you can use a slice flag.

`--strict-mode`
`--strict-name plan-all --strict-name apply-all`
`TG_STRICT_NAME=plan-all,apply-all`

```go
		&cli.BoolFlag{
			Name:        StrictModeFlagName,
			EnvVar:      StrictModeEnvName,
			Destination: &opts.StrictMode,
			Usage:       ".....",
		},
		&cli.SliceFlag[string]{
			Name:        StrictControlNameFlagName,
			EnvVar:      StrictControlNameEnvName,
			Destination: &opts.StrictControlNames,
			Usage:       ".....",
		},
```

Where `opts.StrictControlNames` is the string slice or you can create separated flags using `for`, but hide them:

```go

for _, controlName := range strictControlNames {
   flagName := StrictControlNamePrefixFlagName+ controlName,
   envName := StrictControlNamePrefixEnvName+ controlName, // TODO: ToUpper, Replace "-" => "_"
   falg := 	&cli.BoolFlag{
			Name:        flagName,
			EnvVar:      envName,
			Hidden: true,
			Usage:       ".....",
                         Action: func(ctx *cli.Context, _ bool) (err error) {
                              opts.StrictControlNames = append(opts.StrictControlNames, strictName)
                        }
		},
}
```

3) It would be ideal to combine the command/flag declaration with deprecation messages and errors into one structure. So that they would be like Siamese twins.

`strict/strict.go`

```go
type Control struct {
	// Error is the error that will be returned when the control is enabled.
	Error error
	// Warning is a warning that will be logged when the control is not enabled.
	Warning string
}

type ControlFlag struct {
	Control
	cli.ActionableFlag
}

func (flag *ControlFlag) RunAction(ctx *cli.Context) error {
	// show warn or return errr

	return flag.ActionableFlag.RunAction(ctx)
}

type ControlCommands []*ControlCommand

func (cmds ControlCommands) GetCLICommands() cli.Commands {
	var cliCmds cli.Commands

	for _, cmd := range cmds {
		//....
	}

	return cliCmds
}

type ControlCommand struct {
	Control
	*cli.Command
}

func (cmd *ControlCommand) GetCLICommand(opts *options.TerragruntOptions) *cli.Command {
	actionFn := cmd.Command.Action

	cmd.Command.Action = func(ctx *cli.Context) error {
		// check `opts.StrictControlNames`, show warn or return errr

		return actionFn(ctx)
	}

	return cmd.Command
}
```

`cli/deprecated_flags.go`
```go
func NewDeprecatedFlags(opts *options.TerragruntOptions) cli.Flags {
	flags := cli.Flags{
		strict.ControlFlag{
			Flag: &cli.BoolFlag{
				Name:   TerragruntIncludeModulePrefixFlagName,
				EnvVar: TerragruntIncludeModulePrefixEnvName,
				Usage:  "When this flag is set output from Terraform sub-commands is prefixed with module path.",
				Hidden: true,
				// Action: func(ctx *cli.Context, _ bool) error {
				//	opts.Logger.Warnf("The %q flag is deprecated. Use the functionality-inverted %q flag instead. By default, Terraform/OpenTofu output is integrated into the Terragrunt log, which prepends additional data, such as timestamps and prefixes, to log entries.", TerragruntIncludeModulePrefixFlagName, commands.TerragruntForwardTFStdoutFlagName)
				//	return nil
				//},
			},
			Control: strict.Control{
				Error:   error...,
				Warning: warnning...,
			},
		},
	}

	return flags
}
```


`cli/deprecated_commands.go`

```go
func DeprecatedCommands(opts *options.TerragruntOptions) cli.Commands {
	var cmds strict.ControlCommands

	for cmdName, runFunc := range replaceDeprecatedCommandsFuncs {
		command := strict.ControlCommand{
			Command: &cli.Command{
				Name:   cmdName,
				Hidden: true,
				// Action: runFunc(opts),
			},
			Control: strict.Control{
				Error:   strictErrors[cmdName],
				Warning: strictWarning[cmdName],
			},
		}
	}

	return cmds.GetCLICommands()
}
```
Everything written above is just an idea for implementation, the name of the variables and everything else still needs to be thought out.

2024-09-20 16:12 UTC, levkohimins commented on internal/strict/strict_test.go
> +				t.Setenv("TG_STRICT_PLAN_ALL", "true")
Thanks for the lesson, now I will also use `t.Setenv`

2024-09-20 16:36 UTC, levkohimins commented
If you accept the idea of ​​keeping the flag and control together, I would make some improvements to the cli to get rid of the `ActionableFlag` interface.

```diff
modified   pkg/cli/flag.go
@@ -13,12 +13,6 @@ var (
 	FlagSplitter = strings.Split
 )
 
-// ActionableFlag is an interface that wraps Flag interface and RunAction operation.
-type ActionableFlag interface {
-	Flag
-	RunAction(*Context) error
-}
-
 type FlagType[T any] interface {
 	libflag.Getter
 	Clone(dest *T) FlagType[T]
@@ -39,6 +33,7 @@ type FlagValue interface {
 type Flag interface {
 	Value() FlagValue
 	GetHidden() bool
+	RunAction(*Context) error
 	// `urfave/cli/v2` uses to generate help
 	cli.DocGenerationFlag
 }
modified   pkg/cli/flags.go
@@ -76,10 +76,8 @@ func (flags Flags) Swap(i, j int) {
 func (flags Flags) RunActions(ctx *Context) error {
 	for _, flag := range flags {
 		if flag.Value().IsSet() {
-			if flag, ok := flag.(ActionableFlag); ok {
-				if err := flag.RunAction(ctx); err != nil {
-					return err
-				}
+			if err := flag.RunAction(ctx); err != nil {
+				return err
 			}
 		}
 	}
```

2024-10-07 20:57 UTC, yhakbar commented on cli/deprecated_commands.go
> +				opts.Logger.Warn(warning)
If a user deliberately activates strict mode, they'll get an error, which will prevent the warning.

If strict mode is off, they won't get an error, which means they'll get the warning.

2024-10-10 20:10 UTC, yhakbar commented
I tried to take in the majority of the feedback. The only things I didn't change where things that would have prevented having a single location to look at for all the deprecated functionality we're controlling with strict mode.

2024-10-15 13:11 UTC, yhakbar commented on internal/strict/strict.go
> +	if strictMode == "true" {
Switched to boolean flag + env var.

2024-10-15 13:11 UTC, yhakbar commented on cli/deprecated_commands.go
> +			control, ok := strict.GetStrictControl(strict.PlanAll)
Fixed. Thanks for catching that.

2024-10-15 13:11 UTC, yhakbar commented on internal/strict/strict.go
> +	if enabled == "true" {
Resolved by changing implementation to use boolean flag logic.

2024-10-15 17:19 UTC, denis256 reviewed
I think we also need integration end to end test to track that strict flag will fail Terragrunt execution

2024-10-15 18:54 UTC, yhakbar commented on README.md
> -
It fails the [markdownlint](https://github.com/gruntwork-io/terragrunt/blob/main/.circleci/config.yml#L118) check, but it doesn't matter much for the sake of CI. I'll revert it.

2024-10-15 20:18 UTC, levkohimins reviewed
You did the great work 👍 

I have a suggestion on how to improve it further, please take a look this [branch](https://github.com/gruntwork-io/terragrunt/tree/feat/adding-strict-package-suggestion).

Key points implemented there:
1)  Command names are not repeated
https://github.com/gruntwork-io/terragrunt/blob/e1b5496e747562883604ec2fb4eb91897854e982/cli/deprecated_commands.go#L16-L24
https://github.com/gruntwork-io/terragrunt/blob/e1b5496e747562883604ec2fb4eb91897854e982/internal/strict/strict.go#L26-L41

2) Deprecated commands and their strict controls are defined in one place.
3) `internal/strict` implements only functionality and does not contain data.
4) No global variables.

If you accept this proposal, it will still require some re-work. For example, with log messages, It looks like a repetition, maybe I missed something.

```
22:02:41.573 WARN   The `plan-all` command is deprecated and will be removed in a future version. Use `terragrunt run-all plan` instead.
22:02:41.573 WARN   'plan-all' is deprecated. Running 'terragrunt run-all plan' instead. Please update your workflows to use 'terragrunt run-all plan', as 'plan-all' may be removed in the future!
```

2024-10-15 20:34 UTC, levkohimins submitted a review, later dismissed

2024-10-16 15:04 UTC, levkohimins approved these changes
LGTM!

2024-10-16 15:24 UTC, merged