WIP: TG stacks
gruntwork-io/terragrunt pull request #3627
Opened 2024-12-05 17:04 UTC by denis256

## Description

Fixes #000.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### Migration Guide

2024-12-19 14:57 UTC, yhakbar commented on cli/commands/stack/command.go
> +		commands.NewNoIncludeRootFlag(opts),
I know this is WIP, but I'm curious about this. Do you think we need this for `stack` commands?

2025-01-07 21:28 UTC, yhakbar requested changes
I have mostly small adjustments requested here.

The most important changes I'm requesting are documentation changes for the docs site and the release notes.

2025-01-07 21:28 UTC, yhakbar commented on cli/commands/stack/action.go
> +				getter.WithInsecure(),
Why are we doing this? Do you mind adding a comment documenting that?

2025-01-07 21:28 UTC, yhakbar commented on cli/commands/stack/action.go
> +func isURL(str string) bool {
Does this mean that `github.com/...` URLs won't be supported?

2025-01-07 21:28 UTC, yhakbar commented on cli/commands/stack/action.go
> +	if fi.IsDir() {
Why are we ever fetching a file? We can just always set it to get a directory, right? Do we recursively fetch the individual files after loading the directory?

2025-01-07 21:28 UTC, yhakbar commented on config/stack.go
> +	Units  []*Unit          `cty:"unit" hcl:"unit,block"`
We should point out in the PR body that we're not supporting recursive stacks yet. It should also make its way to the release notes.

2025-01-07 21:28 UTC, yhakbar commented on config/stack.go
> +	attrs, err := localsBlock[0].JustAttributes()
Is this always how locals work? The first block is the only one that matters? If so, we should either throw an error if users use multiple locals blocks, or properly combine them all.

2025-01-07 21:28 UTC, yhakbar commented on config/stack.go
> +			// short an return an error.
```suggestion
			// short and return an error.
```

2025-01-07 21:28 UTC, yhakbar commented on config/unit.go
> +// Unit represents a list of units.
No it doesn't? It represents a single unit, right?

2025-01-07 21:28 UTC, yhakbar commented on config/unit.go
> +	Name   string `cty:"name"    hcl:",label"`
NIT: Let's keep the `cty` and `hcl` tags on the same side, please.

2025-01-07 21:28 UTC, yhakbar commented on config/unit.go
> +func (s *StackConfigFile) ToCtyValue() (cty.Value, error) {
Do we need to have the file available as a cty value right now? We're going to integrate reference to the generating `terragrunt.stack.hcl` file in the future once we support a `values` attribute, but is this doing anything right now?

2025-01-07 21:28 UTC, yhakbar commented on docs/_docs/04_reference/cli-options.md
> +The `terragrunt stack` commands provide a new interface for managing collections of Terragrunt units defined in `terragrunt.stack.hcl` files.
```suggestion
The `terragrunt stack` commands provide an interface for managing collections of Terragrunt units defined in `terragrunt.stack.hcl` files.
```

Let's try to keep these docs evergreen.

2025-01-07 21:28 UTC, yhakbar commented on docs/_docs/04_reference/cli-options.md
> +These commands simplify the process of handling multiple infrastructure units by grouping them into a "stack," reducing code duplication and streamlining operations across environments.
```suggestion
These commands simplify the process of handling multiple infrastructure units by grouping them into a "stack", reducing code duplication and streamlining operations across environments.
```

2025-01-07 21:28 UTC, yhakbar commented on docs/_docs/04_reference/cli-options.md
> +The `terragrunt stack generate` command is used to generate a stack of Terragrunt `hcl` files based on the configuration provided in the `terragrunt.stack.hcl` file.
```suggestion
The `terragrunt stack generate` command is used to generate a stack of `terragrunt.hcl` files based on the configuration provided in the `terragrunt.stack.hcl` file.
```

2025-01-07 21:28 UTC, yhakbar commented on cli/commands/stack/action.go
> +func isURL(str string) bool {
It might be better to see if the source starts with `.` or `/` to indicate that it's a relative or absolute file path respectively.

2025-01-07 21:28 UTC, yhakbar commented on options/options.go
> +	TerragrungStackConfigPath string
Typo. `TerragrungStackConfigPath` --> `TerragruntStackConfigPath`

2025-01-08 19:44 UTC, denis256 commented on cli/commands/stack/action.go
> +func isURL(str string) bool {
In case of `github.com/` you don't know if it is local directory or remote... added workaround to check for `//`

2025-01-08 19:51 UTC, yhakbar commented on cli/commands/stack/action.go
> +func isURL(str string) bool {
I was saying that we can require that local sources always start with `./` for a relative path or `/` for an absolute path.

I'm not sure a user would ever want to do this, but could they define their stack definition at the root of a repository?

e.g.

`github.com/acme/my-favorite-stack`

2025-01-08 20:16 UTC, denis256 commented on cli/commands/stack/action.go
> +				getter.WithInsecure(),
Removed, it was used for local tests/verification of handling symlinks

2025-01-08 20:16 UTC, denis256 commented on cli/commands/stack/action.go
> +	if fi.IsDir() {
Are copied files recursively even if we have multiple subdirectories

2025-01-08 20:19 UTC, denis256 commented on config/stack.go
> +	Units  []*Unit          `cty:"unit" hcl:"unit,block"`
Updated description

2025-01-08 20:20 UTC, denis256 commented on config/stack.go
> +	attrs, err := localsBlock[0].JustAttributes()
I added a check for multiple blocks to get an error in the case of multiple locals.

2025-01-08 20:25 UTC, denis256 commented on config/unit.go
> +func (s *StackConfigFile) ToCtyValue() (cty.Value, error) {
Merged unit.go with stack.go since we only used unit structure from it.

2025-01-08 20:50 UTC, yhakbar commented
@denis256 , if you don't mind, could you put the stacks command behind an experiment flag for now? Users should have to opt-in to use stacks until we're ready for general usage so that we can feel more comfortable changing the API.

2025-01-09 14:54 UTC, yhakbar commented on cli/commands/stack/action.go
> +		return errors.New("No command specified")
Sorry, I didn't think of this until now, but could you return a help message instead of only throwing an error? I think that's a better pattern to follow for commands with required arguments.

2025-01-09 15:06 UTC, yhakbar commented on config/stack.go
> +		return errors.New(fmt.Sprintf("only one locals block is allowed %s stack file, "+
Let's change this to:

"Only one locals block is allowed per stack file, but found %d in %s"

2025-01-09 15:13 UTC, yhakbar commented on test/fixtures/stacks/remote/terragrunt.stack.hcl
> +	source = "github.com/gruntwork-io/terraform-google-sql.git//modules/cloud-sql?ref=${local.version}"
Why are we using this for our tests? Also, this isn't a unit but a module, so this is a little confusing. 

If you need to be able to reference a remote fixture in the Terragrunt repo that isn't tagged yet, you can use the commit. If the issue is squashed commits from merges, we can update the commit after the squash or merge in the fixture as a separate PR.

2025-01-09 16:51 UTC, yhakbar approved these changes
🚀

2025-01-09 16:53 UTC, merged